print("el hombre")
print("A man in spanish")
print("el nino")
print("a boy in spanish")
print("la nina")
print("a girl in spanish")
print("la mujer")
print("a woman in spanish")
print("uno")
print("one in spanish")
print("dos")
print("two in spanish")
print("tres")
print("three in spanish")
print("cuatro")
print("four in spanish")
print("cinco")
print("five in spanish")
print("seis")
print("six in spanish")
print("siete")
print("seven in spanish")
print("ocho")
print("eight in spanish")
print("nueve")
print("nine in spanish")
print("diez")
print("ten in spanish")