print(*"Glad to see you back! Let's learn some more Spanish words together!")
print("lets get started!")
print("mucho gusto")
print("Nice to meet you in Spanish")
print("buenos dias")
print("Good morning in Spanish")
print("buenas tardes")
print("Good afternoon in Spanish")
print("buenas noches")
print("Good night in Spanish")
print("por favor")
print("Please in Spanish")
print("gracias")
print("Thank you in Spanish")
print("de nada")
print("You're welcome in Spanish")
print("lo siento")
print("I'm sorry in Spanish")
print("salud")
print("Bless you in Spanish")
print("adios")
print("Goodbye in Spanish")
print("hasta luego")
print("See you later in Spanish")
print("hasta manana")
print("See you tomorrow in Spanish")
print("que tengas un buen dia")
print("Have a nice day in Spanish")
print("wante to learn more?")
print("aprender")
print("To learn in Spanish")
print("jugar")
print("To play in Spanish")
print("leer")
print("To read in Spanish")
print("escribir")
print("To write in Spanish")
print("escuchar")
print("To listen in Spanish")
print("hablar")
print("To speak in Spanish")
print("comprender")
print("To understand in Spanish")
print("practicar")
print("To practice in Spanish")
print("estudiar")
print("To study in Spanish")