print("la manzana")
print("A apple in Spanish")
print("la leche")
print ("A milk in Spanish")
print("el queso")
print("A cheese in Spanish")
print("el pan")
print("A bread in Spanish")
print("el arroz")
print("A rice in Spanish")
print("el pollo")
print("A chicken in Spanish")
print("el pescado")
print("A fish in Spanish")
print("las verduras")
print("Vegetables in Spanish")
print("las frutas")
print("Fruits in Spanish")
print("el desayuno")
print("Breakfast in Spanish")
print("come on you can do it")
print("el almuerzo")
print("Lunch in Spanish")
print("la cena")
print("Dinner in spanish")
print("el postre")
print("Dessert in Spanish")